from __future__ import annotations

import json
import concurrent.futures
import os
from dataclasses import dataclass

import prompttestenv.logger as logger
from prompttestenv.api import (
    cosine_similarity,
    get_llm_response,
    get_text_embedding,
    is_local_provider,
)
from prompttestenv.models import (
    TestCaseResult,
    JudgeConfig,
    JUDGE_TYPE_LLM,
    JUDGE_TYPE_SIMILARITY,
    JUDGE_TYPE_ASSERT,
    GLOBAL_MODE_NONE,
)


def _evaluate_llm_judge(
    prompt: TestCaseResult | TempPrompt,
    candidate_response: str,
    judge_config: JudgeConfig,
    local_media_paths: list[str] | None = None,
) -> tuple[int, str]:
    """Execute evaluation using the judge LLM.

    Args:
        prompt: The TestCaseResult or TempPrompt containing prompt and criteria.
        candidate_response: The response text generated by the candidate.
        judge_config: JudgeConfig instance.
        local_media_paths: Optional local paths to media files attached as ground truth.

    Returns:
        A tuple of (score, reasoning) where score is 1-10 and reasoning is the judge's text explanation.
    """
    evaluation_template = judge_config.test_judge.evaluation_template
    sys_prompt = judge_config.test_judge.evaluation_system_prompt

    if not evaluation_template:
        return -1, "Error: Missing evaluation_template in judge_config."

    try:
        evaluation_prompt = evaluation_template.format(
            user_prompt=prompt.prompt,
            candidate_response=candidate_response,
            criteria=prompt.criteria,
        )
    except KeyError as exc:
        return -1, f"Error in evaluation template: missing field {exc}"

    if local_media_paths:
        # Prepended, not appended: a provider without native file support
        # inlines the attachments AHEAD of the whole prompt, so a note in the
        # tail would announce a file the judge read several thousand tokens
        # earlier. Head position puts it right after the content it describes.
        names = ", ".join(os.path.basename(path) for path in local_media_paths)
        many = len(local_media_paths) > 1
        subject = "files for the test are" if many else "file for the test is"
        evaluation_prompt = (
            f"[SYSTEM NOTE]: The original {subject} attached ({names}). "
            f"Use {'them' if many else 'it'} as ground truth to verify the "
            "candidate's response.\n\n"
        ) + evaluation_prompt

    provider = judge_config.test_judge.provider
    model_name = judge_config.test_judge.model
    judge_temp = judge_config.test_judge.temperature
    thinking = judge_config.test_judge.thinking
    disable_safety = judge_config.test_judge.disable_safety

    try:
        result = get_llm_response(
            provider=provider,
            model_name=model_name,
            system_instruction=sys_prompt,
            user_prompt=evaluation_prompt,
            local_media_paths=local_media_paths,
            temp=judge_temp,
            thinking=thinking,
            response_mime_type="application/json",
            disable_safety=disable_safety,
        )
        parsed = json.loads(result.text)
        if isinstance(parsed, list):
            parsed = parsed[0] if parsed and isinstance(parsed[0], dict) else {}
        if not isinstance(parsed, dict):
            return -1, f"Error: LLM response did not parse as a dict: {result.text}"

        reasoning = parsed.get("reasoning", "")
        raw_score = parsed.get("score")
        try:
            score = int(raw_score)
        except (TypeError, ValueError):
            return -1, f"Error: LLM response 'score' field is missing or not numeric: {raw_score!r}"

        # A real score from the judge, only out of range: clamp it exactly like
        # _evaluate_assert/_evaluate_similarity do, rather than treating a
        # badly-formed real score as a system error.
        score = max(1, min(10, score))
        return score, str(reasoning)
    except Exception as exc:
        return -1, f"LLM evaluation failed: {exc}"


def _evaluate_similarity(
    criteria: str,
    candidate_response: str,
    judge_config: JudgeConfig,
) -> tuple[int, str]:
    """Execute similarity evaluation using embedding cosine similarity.

    Args:
        criteria: Reference target text expected in the response.
        candidate_response: The response text generated by the candidate.
        judge_config: JudgeConfig instance.

    Returns:
        A tuple of (score, reasoning) where score is 1-10 scaled from the cosine similarity.
    """
    provider = judge_config.similarity_judge.provider
    model = judge_config.similarity_judge.model

    if not candidate_response.strip():
        return 1, "Empty candidate response. Score set to minimum (1)."
    if not criteria.strip():
        return 1, "Empty reference criteria/target response. Score set to minimum (1)."

    try:
        emb_cand = get_text_embedding(provider, model, candidate_response)
        emb_ref = get_text_embedding(provider, model, criteria)
        sim = cosine_similarity(emb_cand, emb_ref)
        
        # Scale cosine similarity from 0.0-1.0 to 1-10
        clamped_sim = max(0.0, min(1.0, sim))
        score = int(round(1.0 + 9.0 * clamped_sim))
        score = max(1, min(10, score))
        
        reasoning = f"Cosine similarity between candidate response and target response is {sim:.4f}."
        return score, reasoning
    except Exception as exc:
        logger.log_error(f"Similarity evaluation failed: {exc}")
        return -1, f"Error: Similarity evaluation failed: {exc}"


def _evaluate_assert(
    criteria: str,
    candidate_response: str,
) -> tuple[int, str]:
    """Execute evaluation using a vanilla Python assertion lambda.

    Args:
        criteria: String expression of a Python lambda function mapping response text to (score, reasoning).
        candidate_response: The response text generated by the candidate.

    Returns:
        A tuple of (score, reasoning) evaluated from the lambda. The score is
        NOT clamped to 1-10: criteria are an unsandboxed lambda written by
        whoever owns the project directory, so keeping it in range (or using
        -1 to deliberately signal "not measured/not applicable") is their
        call, not the framework's. -1 is only returned on the framework's own
        initiative when it could not get a score out of the lambda at all
        (malformed syntax, a runtime exception, or a non-tuple return).
    """
    expr = criteria.strip()
    if not expr.startswith("lambda"):
        expr = f"lambda {expr}"

    try:
        # Evaluate the lambda expression directly
        func = eval(expr)
        res = func(candidate_response)
        if isinstance(res, tuple) and len(res) == 2:
            score, reasoning = res
            return int(score), str(reasoning)
        else:
            return -1, f"Error: Assert lambda did not return a (score, reasoning) tuple. Got: {res}"
    except Exception as exc:
        return -1, f"Error: Assert evaluation failed: {exc}"


@dataclass
class TempPrompt:
    """Temporary prompt used to wrap global criteria text for LLM judge evaluations."""
    prompt: str
    criteria: str


def evaluate_with_judge(
    prompt: TestCaseResult,
    candidate_response: str,
    judge_config: JudgeConfig,
    local_media_paths: list[str] | None = None,
) -> dict:
    """Run judge evaluation on a single candidate response.

    Calls the configured judge or calculates similarity/assert depending on the
    configured judge_type.

    Args:
        prompt: The TestCaseResult containing the original prompt and criteria.
        candidate_response: The LLM-generated text to evaluate.
        judge_config: JudgeConfig instance.
        local_media_paths: Optional local file paths to pass to the judge. Only
            the llm-judge evaluators take them; similarity and assert score the
            response text alone, by design.

    Returns:
        Dict with keys: score, reasoning, global_score, global_reasoning.
    """
    def run_task_eval():
        judge_type = getattr(prompt, "judge_type", JUDGE_TYPE_LLM)
        if judge_type == JUDGE_TYPE_LLM:
            return _evaluate_llm_judge(prompt, candidate_response, judge_config, local_media_paths)
        elif judge_type == JUDGE_TYPE_SIMILARITY:
            return _evaluate_similarity(prompt.criteria, candidate_response, judge_config)
        elif judge_type == JUDGE_TYPE_ASSERT:
            return _evaluate_assert(prompt.criteria, candidate_response)
        else:
            return -1, f"Error: Unknown judge_type '{judge_type}'."

    def run_global_eval():
        g_criteria = judge_config.global_criteria
        g_mode = getattr(g_criteria, "mode", GLOBAL_MODE_NONE)
        if g_mode == GLOBAL_MODE_NONE:
            return -1, "N/A"
        elif g_mode == JUDGE_TYPE_LLM:
            mock_prompt = TempPrompt(prompt=prompt.prompt, criteria=g_criteria.llm_judge_criteria)
            return _evaluate_llm_judge(mock_prompt, candidate_response, judge_config, local_media_paths)
        elif g_mode == JUDGE_TYPE_SIMILARITY:
            return _evaluate_similarity(g_criteria.similarity_criteria, candidate_response, judge_config)
        elif g_mode == JUDGE_TYPE_ASSERT:
            return _evaluate_assert(g_criteria.assert_criteria, candidate_response)
        else:
            return -1, f"Error: Unknown global evaluation mode '{g_mode}'."

    try:
        # A local backend serves one model at a time, so running the task and
        # global judges concurrently would only queue them against each other,
        # or force a second load into VRAM.
        if is_local_provider(judge_config.test_judge.provider):
            score, reasoning = run_task_eval()
            global_score, global_reasoning = run_global_eval()
            return {
                "score": score,
                "reasoning": reasoning,
                "global_score": global_score,
                "global_reasoning": global_reasoning,
            }

        with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
            future_task = executor.submit(run_task_eval)
            future_global = executor.submit(run_global_eval)
            score, reasoning = future_task.result()
            global_score, global_reasoning = future_global.result()

            return {
                "score": score,
                "reasoning": reasoning,
                "global_score": global_score,
                "global_reasoning": global_reasoning,
            }
    except Exception as exc:
        logger.log_error(f"Evaluation dispatcher failed: {exc}")
        return {
            "score": -1,
            "reasoning": f"Error: {str(exc)}",
            "global_score": -1,
            "global_reasoning": "Error",
        }

